name: merge-split-llm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - pyyaml
  - tqdm
  - pip
  - pip:
      - lightning
