name: merge-split-llm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - pyyaml
  - tqdm
  - pip
  - scikit-learn
  - scikit-image
  - matplotlib
  - ipympl
  - ipython
  - jupyterlab
  - ipywidgets
  - pip:
      - pytorch-lightning
